services:
  quizify-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: alerr04/quizify-api:0.9.1-dev
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3010
    ports:
      - "3010"
    volumes:
      - ./logs:/app/logs:rw
    restart: unless-stopped