version: '3.8'

services:
  quizify-api:
    image: alerr04/quizify-api:0.9.0-dev
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3010
      # URLs del frontend permitidas para CORS (separadas por coma)
      CORS_ORIGINS: "https://taller-frontend-bhaobk-607ebf-173-212-248-96.traefik.me"
    ports:
      - "3010"
    volumes:
      - ./logs:/app/logs:rw
    restart: unless-stopped

    